# All references from this file to other files should be relative links from this file's location.
version: '3'
services:

  api_aws: # This should match the name of a folder at the root of the repo.
    container_name: api_aws
    build:
      context: .
      dockerfile: ./api_aws/Dockerfile
    command:
      - "uvicorn"
      - "app:my_app"
      - "--reload"
      - "--host"
      - "0.0.0.0" # Makes container's port accessable from host running Docker.
      - "--port"
      - "8000"
    ports:
      - 8000:8000
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    volumes:
      - ./api_aws/src/app.py:/usr/src/api_aws/src/app.py
      - ./api_aws/src/__init__.py:/usr/src/api_aws/src/__init__.py
      - ./scripts/create_zappa_package.sh:/usr/src/scripts/create_zappa_package.sh # Needed to deploy.
      - ./api_aws/zappa_settings.json:/usr/src/api_aws/zappa_settings.json # Needed to deploy.
    healthcheck:
      test:
        - "CMD"
        - "curl"
        - "http://localhost:8000/internal/ping"
      interval: 3s
      timeout: 1s
